### ISSUE TITLE
missing sql auto 

### ISSUE THREAD

**Issue by egyshell** [R34P3R2/R-Box#1]
here is the error 

Have You Got Sqlmap installed? y/n? y
sudo: ./sqlauto: command not found
Traceback (most recent call last):
  File "menu.py", line 337, in <module>
    main()
  File "menu.py", line 334, in main
    com()
  File "menu.py", line 286, in com
    if xsstraccerin == ("y"):
UnboundLocalError: local variable 'xsstraccerin' referenced before assignment

**Comment by R34P3R2** [comment]
Thank You For Reporting This Problem we will fix it as fast as we can.

**Comment by R34P3R2** [comment]
The Problem Has Been Resolved :D
